---
- name: Provision new host
  hosts: foreman_rhel7
  tasks:
  - name: Set content in /etc/motd 
    copy:
      content: Authorized use only!
      dest: /etc/motd
      mode: 644
      owner: root
      group: root

  - name: Install vim package
    yum:
      name: vim
      state: present

  - name: Register with activationkey
    redhat_subscription:
      state: present
      activationkey: testlabkey
      org_id: Test_Lab

#  - name: Show subscription_status
#    debug:
#      msg: >
#        Subscription Status: {{ foreman.subscription_status_label }}

#  - name: Show Errata Counts
#    debug:
#      msg: >
#        Bug fixes: {{ foreman.content_facet_attributes.errata_counts.bugfix }},
#        Security: {{ foreman.content_facet_attributes.errata_counts.security }},
#        Enhancement: {{ foreman.content_facet_attributes.errata_counts.enhancement }},
#        Total: {{ foreman.content_facet_attributes.errata_counts.total }}