- name: Guest Creation
  gather_facts: no
  vars_files:
    - lab_vcenter_vars.yml
  hosts: localhost
  collections:
  - name: community.vmware
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      community.vmware.vmware_guest:
        name: "{{ vm_name }}"
        state: present
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no 
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        esxi_hostname: "{{ esxi_hostname }}"
        networks:
          - name: "{{ network }}"
            start_connected: yes
            device_type: vmxnet3
            type: static
            ip: "{{ vm_ipaddr }}"
            netmask: 255.255.255.0
            gateway: 192.168.122.1
        wait_for_ip_address: yes
        customization:  
          domain: "{{ guest_domain }}"
          dns_servers:
            - "{{ dns_server }}"
          dns_suffix:
            - "{{ guest_domain }}"
        wait_for_customization: yes
      register: vm_result

    - name: Assert that VM is created
      assert:
        that:
          - "vm_result.changed"
