- name: Guest Creation
  gather_facts: no
  vars_files:
    - lab_vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      vmware_guest:
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no 
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        networks:
          - name: "{{ network }}"
            ip: 192.168.122.122
            netmask: 255.255.255.0
            gateway: 192.168.122.122
        customization:
          dns_servers: "{{ dns_server }}"
        wait_for_ip_address: yes
      register: vm_result

    - name: Assert that VM is created
      assert:
        that:
          - "vm_result.changed"
