- name: Create a snapshot
  vars_files:
    - ocpcluster_vars.yml
  hosts: localhost
  tasks:
    - name: Create a snapshot of {{ guest_name }}
        community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/datastore1/{{ guest_name }}/"
        name: "{{ guest_name }}"
        state: present
        snapshot_name: snap1
        description: "{{ guest_name }}"_snap1
      delegate_to: localhost
      register: vm_result
