---
- name: Remove a snapshot
  hosts: localhost
  ignore_errors: yes
  gather_facts: yes
  vars:
    vcenter_hostname: 10.100.1.xxx
    vcenter_username: xxxx
    vcenter_password: xxxxxx
    datacenter_name: ocpdc
    guest_name: xxxxx
#  vars_files:
#        - ocpcluster_vars.yml
  tasks:  
    - name: Remove a snapshot of {{ guest_name }}
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}"
        name: "{{ guest_name }}"
        state: absent
        snapshot_name: snap3
        validate_certs: no
      delegate_to: localhost
...
