- name: Esxi maintenance
  gather_facts: yes
  vars_files:
    - lab_vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: start main1 
      vmware_maintenancemode:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no 
        esxi_hostname: "{{ esxi_hostname }}"
        evacuate: yes
        validate_certs: no
        timeout: 3600
