
---
- name: ESXi patching
  hosts: localhost
  gather_facts: true
  vars_files:
    - vcenter_vars.yml
  tasks:
    - name: ESXi maintenance
      vmware_maintenancemode:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ inventory_hostname }}"
        evacuate: yes
        validate_certs: no
        timeout: 3600
        state: present
      delegate_to: localhost
  
