---
- name: Register new host
  hosts: all
  tasks:
  - name: Set content in /etc/motd 
    copy:
      content: Authorized use only!
      dest: /etc/motd
      mode: 644
      owner: root
      group: root

  - name: Install the nginx rpm from a remote repo
    yum:
      name: https://satellite69.test.com/pub/katello-ca-consumer-latest.noarch.rpm
      state: present

  - name: Register with activationkey
    redhat_subscription:
      state: present
      activationkey: testlabkey
      org_id: Test_Lab
#      force_register: yes

  - name: Install vim package
    yum:
      name: vim
      state: present