---
- name: Register VM to Satellite
  gather_facts: no
  vars_files:
    - lab_vcenter_vars.yml
  hosts: "{{ vm_name }}"
  tasks:
  - name: Register with activationkey
    redhat_subscription:
      state: present
      activationkey: testlabactivationkey
      org_id: Test_Lab
      autosubscribe: true