---
- name: Remove virtual machine
  gather_facts: no
  vars_files:
    - lab_vcenter_vars.yml
  hosts: localhost
  tasks:

    - name: Stop "{{ vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: shutdownguest
      delegate_to: localhost

    - name: Delete "{{ vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        name: "{{ vm_name }}"
        state: absent
      delegate_to: localhost      